# Generated by Django 5.0.1 on 2024-04-10 15:05

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Type_E', models.IntegerField(default=0)),
                ('Address_One', models.CharField(max_length=255)),
                ('Address_Two', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(max_length=255)),
                ('County', models.CharField(max_length=255)),
                ('Postcode', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(max_length=15)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('last_login', models.DateTimeField(default=datetime.date.today)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=datetime.date.today)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('ContractID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Type_E', models.IntegerField(default=0)),
                ('Guid', models.BinaryField()),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('path', models.CharField(max_length=4096)),
                ('Type_E', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.IntegerField(default=0)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('DocumentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.document')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Type_E', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_ID', models.IntegerField(default=0)),
                ('DocumentPack_ID', models.IntegerField(default=0)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Job_Name', models.CharField(max_length=255)),
                ('Job_Description', models.TextField()),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='JobID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.job'),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=255, null=True)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Histories',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Security_Permissions', models.BooleanField(default=False)),
                ('Document_Permissions', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy_UserID', models.IntegerField(default=0)),
                ('Created_Date', models.IntegerField(default=0)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.job')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='RoleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.role'),
        ),
    ]
