# Generated by Django 5.0.1 on 2024-02-12 21:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('path', models.CharField(max_length=4096)),
                ('Type_E', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Job_Name', models.CharField(max_length=255)),
                ('Job_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Security_Permissions', models.BooleanField(default=False)),
                ('Document_Permissions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Type_E', models.IntegerField(default=0)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('Address_One', models.CharField(max_length=255)),
                ('Address_Two', models.CharField(max_length=255)),
                ('County', models.CharField(max_length=255)),
                ('Postcode', models.CharField(max_length=10)),
                ('Email_address', models.CharField(max_length=255)),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Created_By_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='models.user')),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.job')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role')),
                ('Updated_By_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user'),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.IntegerField(default=0)),
                ('RoleID', models.IntegerField(default=0)),
                ('CreatedBy_UserID', models.IntegerField(default=0)),
                ('Created_Date', models.IntegerField(default=0)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user'),
        ),
        migrations.CreateModel(
            name='DocumentPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_ID', models.IntegerField(default=0)),
                ('DocumentPack_ID', models.IntegerField(default=0)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Type_E', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.IntegerField(default=0)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('DocumentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.document')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('ContractID', models.AutoField(primary_key=True, serialize=False)),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Type_E', models.IntegerField(default=0)),
                ('Guid', models.BinaryField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateField(default=datetime.date.today)),
                ('Updated_Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
    ]
