# Generated by Django 5.0.1 on 2024-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'verbose_name_plural': 'Password Histories'},
        ),
    ]
