# Generated by Django 5.0.1 on 2024-02-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_passwordhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name_plural': 'Document Categories'},
        ),
    ]
