# Generated by Django 5.0.1 on 2024-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Document_file',
            field=models.FileField(blank=True, null=True, upload_to='data_entry/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_contract',
            field=models.FileField(blank=True, null=True, upload_to='data_entry/documents'),
        ),
    ]
