# Generated by Django 5.0.1 on 2024-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
