# Generated by Django 5.0.1 on 2024-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_document_document_file_user_user_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
