# Generated by Django 5.0.1 on 2024-02-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='UserID',
        ),
    ]
