# Generated by Django 5.0.1 on 2024-02-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_job_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='JobID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.job'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role'),
        ),
    ]
