# Generated by Django 5.0.1 on 2024-02-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_jobrole_jobid_alter_jobrole_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='UserID',
        ),
    ]
