# Generated by Django 5.0.1 on 2024-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_role_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Created_By_User',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Updated_By_User',
        ),
        migrations.AlterField(
            model_name='user',
            name='Address_Two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
