# Generated by Django 5.0.1 on 2024-03-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='JobID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='RoleID',
        ),
    ]
